### PR TITLE
Fixed issues, now sliders can be adjusted with mouse scroll wheel

### PR DESCRIPTION
**Pull request by Equbuxu**

### CODE REVIEW

**Review by flabbet — CHANGES_REQUESTED** [review]
All good, but I would increase scroll sensitivity. It's too slow in my opinion. Or add it as Dependency Property.

**Comment by Equbuxu** [comment]
> All good, but I would increase scroll sensitivity. It's too slow in my opinion. Or add it as Dependency Property.

Actually, this is by design since the whole point of the feature is to allow more precise control (it's hard to finely adjust the slider otherwise). I can add it as a dependency property but it should stay low in PixiEditor

**Comment by flabbet** [comment]
For PixiEditor it's fine I guess, but I would add it as a dependency property for anyone who would like to use it in their project.

**Comment by Equbuxu** [comment]
Added dependency properties, they are not completely polished in that you have to specify values from 0 to 1 even though values in textboxes go from 0 to 255. I'm going to rework this system anyway in 3.0.0, so I figured it will be fine as-is for now.

**Review by flabbet — APPROVED** [review]
Goooood

**Pull request merged**
